FROM confluentinc/cp-kafka-connect:7.6.1
RUN wget https://repo1.maven.org/maven2/org/mongodb/kafka/mongo-kafka-connect/1.13.0/mongo-kafka-connect-1.13.0-all.jar
RUN cp mongo-kafka-connect-1.13.0-all.jar /usr/share/confluent-hub-components